# Generated by Django 5.2.4 on 2025-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=30)),
                ('usrpwd', models.CharField(max_length=5)),
            ],
        ),
    ]
