# Generated by Django 5.2.4 on 2025-07-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfire', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='userbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdname', models.CharField(max_length=30)),
                ('qty', models.IntegerField(max_length=500)),
                ('mrp', models.IntegerField(max_length=100000)),
                ('sp', models.IntegerField(max_length=100000)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=50)),
                ('phn', models.IntegerField(max_length=10)),
            ],
        ),
    ]
