# Generated by Django 5.2.4 on 2025-07-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starfire', '0004_userlog_b2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbill',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='userbill',
            name='sp',
        ),
    ]
